name: Eclectic E. Tsai
favicon: null
layout_spectrum: 0.7541424073278904
typography_spectrum: 0.0690940108615905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9325762409716845
  lightness: 0.2815523883327842
  saturation: 0.42127605178393424
  rhythmicContrast: 0.4790724664926529
purpose: []
